# Generated by Django 4.1.4 on 2023-08-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='hosting_date',
            new_name='payment_date',
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='externallinks',
            name='excluded',
            field=models.JSONField(default=['mailto:', 'tel:']),
        ),
    ]
