# Generated by Django 4.1.4 on 2023-08-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_hosting_date_site_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallinks',
            name='excluded',
            field=models.JSONField(),
        ),
    ]
